### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid step value 5

### ISSUE THREAD

**Issue by pranaypatel512** [badoualy/stepper-indicator#4] opened 2016-06-16 05:39 UTC
Thanks for library. 
I have latest version of library and when trying to swipe step, I am getting below error log.
same issue I see #2 

`--------- beginning of crash
06-16 11:02:50.091 12728-12728/com.badoualy.stepperindicator.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                      Process: com.badoualy.stepperindicator.sample, PID: 12728
                                                                                      java.lang.IllegalArgumentException: Invalid step value 5
                                                                                          at com.badoualy.stepperindicator.StepperIndicator.setCurrentStep(StepperIndicator.java:272)
                                                                                          at com.badoualy.stepperindicator.StepperIndicator.onPageSelected(StepperIndicator.java:386)
                                                                                          at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1867)
                                                                                          at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:625)
                                                                                          at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:609)
                                                                                          at android.support.v4.view.ViewPager.onTouchEvent(ViewPager.java:2181)
                                                                                          at android.view.View.dispatchTouchEvent(View.java:9297)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2549)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                          at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                                          at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                                          at android.app.Activity.dispatchTouchEvent(Activity.java:2769)
                                                                                          at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                                          at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                                          at android.view.View.dispatchPointerEvent(View.java:9517)
                                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4242)
                                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4108)
                                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3654)
                                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3707)
                                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3673)
                                                                                          at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3799)
                                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3681)
                                                                                          at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3856)
                                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3654)
                                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3707)
                                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3673)
                                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3681)
                                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3654)
                                                                                          at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5969)
                                                                                          at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5908)
                                                                                          at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5869)
                                                                                          at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6072)
                                                                                          at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
                                                                                          at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                          at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
`

**Comment by badoualy** [comment] 2016-06-16 05:42
Duplicate of https://github.com/badoualy/stepper-indicator/issues/2
Didn't push yet :)
5 minutes :)

**Closed as completed by badoualy** 2016-06-16 05:42 UTC

**Comment by badoualy** [comment] 2016-06-16 05:44
`compile 'com.github.badoualy:stepper-indicator:1.0.1'`
Should fix it

**Comment by pranaypatel512** [comment] 2016-06-16 05:50
Thanks @badoualy  for quick reply. done.
